name: Stage-Deploy Resource

variables:
- group: azure-environment

parameters:
- name: spring_cloud_name
  default: $(SPRING_CLOUD_NAME)
- name: resource_group
  default: $(RESOURCE_GROUP)
- name: application_name
- name: service_connection_name
  default: $(SERVICE_CONNECTION_NAME)
  
trigger: none

pool:
  vmImage: 'ubuntu-20.04'

resources:
  pipelines:
  - pipeline: build_from_github
    source: Build from GitHub
    trigger: none

stages: 
- stage: deploy_staging
  displayName: Staging Deployment
  jobs:
  - job: deploy_staging
    displayName: Staging Deployment
    steps:
    - download: build_from_github
      artifact: build  
    - task: AzureSpringCloud@0
      timeoutInMinutes: 20
      inputs:
        azureSubscription: ${{parameters.service_connection_name}}
        Action: 'Deploy'
        AzureSpringCloud: '${{parameters.spring_cloud_name}}'
        AppName: '${{parameters.application_name}}'
        UseStagingDeployment: true
        Package: '$(PIPELINE.WORKSPACE)/build_from_github/build/*${{parameters.application_name}}*.jar'
    

- stage: move_to_production
  displayName: Move to Production
  jobs:
  - job: move_to_production
    displayName: Move to Production
    steps:
    - task: AzureSpringCloud@0
      inputs:
        azureSubscription: ${{parameters.service_connection_name}}
        Action: 'Set Production'
        AzureSpringCloud: '${{parameters.spring_cloud_name}}'
        AppName: '${{parameters.application_name}}'
        UseStagingDeployment: true

